

# This YML File uses 'awsconfig.json' file on the root directory
# for the configurations.
# awsconfig:
#   bucket_name: <bucket for the images>
#   bucket_arn: <bucket for the images>

service: xpectrum-image-processor

package:
  exclude:
    - 'venv/**'
    - 'env/**'
    - '__pycache__/**'
    - '.pytest_cache/**'
    - '.serverless/**'
    - '.coverage'

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:DeleteObject
        - s3:GetObject
      Resource: 
        - arn:aws:s3:::${self:custom.bucketname}

  environment:
    bucketname: ${self:custom.bucketname}

custom:
  bucketname: "tac-cms-bucket-dev"

functions:
  xpectrum_img_processor_api:
    handler: src/xpectrum_img_processor_api.handler    
    layers: 
      - ${file(awsconfig.json):layer_arn}
    timeout: 900


