

# This YML File uses 'awsconfig.json' file on the root directory
# for the configurations.
# awsconfig:
#   s3ResourceBucket: <bucket for the images>

service: xpectrum-image-processo:r

package:
  exclude:
    - 'venv/**'
    - 'env/**'
    - '__pycache__/**'
    - '.pytest_cache/**'
    - '.serverless/**'
    - '.coverage'

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:DeleteObject
        - s3:GetObject
      Resource: ${file(awsconfig.json):bucket_arn}
  environment:
    bucketname: ${file(awsconfig.json):bucketname}

functions:
  xpectrum_img_processor_api:
    handler: src/xpectrum_img_processor_api.handler    

  xpectrum_img_s3_auto_resizer:
    handler: src/xpectrum_img_s3_auto_resizer.handler
    events:
      - s3:
          bucket: ${file(config.json:bucket_name)}
          events: s3:ObjectCreated:*
          rules:
            - prefix: media/
            - suffix:
              - jpg
              - jpeg
              - png

    layers: 
      - arn:aws:lambda:ap-southeast-1:940508673835:layer:image-processing:1
    timeout: 900




